#!/bin/sh
# Startup script for go questionnaire programm
# www.der-taegliche-admin.de/2010/06/25/eigenes-start-stop-shell-script-erstellen/
INSTANZ="Go questionnaire"
BPDIR=/opt/go-questionnaire
Pidfile=/var/run/go-questionnaire/prog.pid
LOGFILE=/var/log/go-questionnaire.log

if [ -f $Pidfile ]
then
	Pid=`cat $Pidfile`
fi

case "$1" in
'start')
		if [ -f $Pidfile ] ; then
				if test `ps -e | grep -c $Pid` = 1; then
						echo "Not starting $INSTANZ - instance already running with PID: $Pid"
				else
						echo "Starting $INSTANZ"
						cd $BPDIR
						#  stackoverflow.com/questions/4699790/
						#  nohup ./go-questionnaire 1>/var/log/out.log 2>/var/log/err.log &
						nohup    ./go-questionnaire >$LOGFILE 2>&1 &

						# Alternative: stdout and stderr into /dev/null
						# nohup ./go-questionnaire &> /dev/null &

						echo $! > $Pidfile

						# $! PID of the most recent background command.
						# stackoverflow.com/questions/5163144/

						# Better: unix.stackexchange.com/questions/74520
						#  > x.log     =>  stdout to logfile
						#  2>&1        =>  stderr to logfile too
						#  
						# nohup ./go-questionnaire >$LOGFILE 2>&1 &

				fi
		else
				echo "Starting $INSTANZ"
				cd $BPDIR
				#./go-questionnaire >$LOGFILE 2>&1 &
				nohup ./go-questionnaire >$LOGFILE 2>&1 &
				echo $! > $Pidfile
		fi
		;;

'stop')
		if [ -f $Pidfile ] ; then
				echo "stopping $INSTANZ"
				kill -15 $Pid
		else
				echo "Cannot stop $INSTANZ - no Pidfile found!"
		fi
		;;

'restart')
		$0 stop
		sleep 5
		$0 start
		;;

'status')
		if [ -f $Pidfile ] ; then
				if test `ps -e | grep -c $Pid` = 0; then
						echo "$INSTANZ not running"
				else
						echo "$INSTANZ running with PID: [$Pid]"
				fi
		else
				echo "$Pidfile does not exist! Cannot process $INSTANZ status!"
				exit 1
		fi
		;;

*)
		echo "usage: $0 { start | stop | restart | status }"
		;;

esac
exit 0
