name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6 # Updated to v6

      - uses: actions/setup-go@v6 # Updated to v6
        with:
          go-version: '1.26.3'

      - name: Debug Go
        run: |
          which go
          go version
          go tool

      - name: Run coverage
        run: |
          mv app-bucket/config-example.json app-bucket/config.json
          mv app-bucket/logins-example.json app-bucket/logins.json
          go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - uses: codecov/codecov-action@v6     # Updated to v6
        with:
          # token for Codecov
          # https://app.codecov.io/github/pbberlin/go-questionnaire/new
          # 1146deea-3f3a-4a66-aff7-1ae68b4ba6ed
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: coverage.out